from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('stammbaum/', views.stammbaum, name='stammbaum'),
    path('stammbaum/gesamt/', views.stammbaum_gesamt, name='stammbaum_gesamt'),
    path('stammbaum/bfs/', views.stammbaum_bfs, name='stammbaum_bfs'),
    path('stammbaum/genogramm/', views.stammbaum_genogramm, name='stammbaum_genogramm'),
    path('stammbaum/fraktal/', views.stammbaum_fraktal, name='stammbaum_fraktal'),
    path('stammbaum/kraft/', views.stammbaum_force, name='stammbaum_force'),
    path('api/stammbaum/gesamt/', views.stammbaum_gesamt_json, name='stammbaum_gesamt_json'),
    path('api/stammbaum/fraktal/', views.stammbaum_fraktal_json, name='stammbaum_fraktal_json'),
    path('api/stammbaum/<int:person_id>/', views.stammbaum_json, name='stammbaum_json'),
    path('personen/', views.personen_liste, name='personen_liste'),
    path('personen/neu/', views.person_neu, name='person_neu'),
    path('personen/<int:pk>/', views.person_detail, name='person_detail'),
    path('personen/<int:pk>/bearbeiten/', views.person_bearbeiten, name='person_bearbeiten'),
    path('karte/', views.karte, name='karte'),
    path('api/karte/', views.karte_json, name='karte_json'),
    path('api/geocode/<str:ort_name>/', views.geocode_ort, name='geocode_ort'),
    path('api/ort/<str:ort_name>/koordinaten/', views.ort_koordinaten_update, name='ort_koordinaten_update'),
    path('api/ort/<str:ort_name>/problem/', views.ort_problem_toggle, name='ort_problem_toggle'),
    path('api/konflikte/count/', views.konflikte_count, name='konflikte_count'),
    path('konflikte/', views.konflikte, name='konflikte'),
    path('statistiken/', views.statistiken, name='statistiken'),
    path('suche/', views.suche, name='suche'),
    path('personen/<int:pk>/partner/hinzufuegen/', views.partner_hinzufuegen, name='partner_hinzufuegen'),
    path('personen/<int:pk>/partner/entfernen/<int:ehe_pk>/', views.partner_entfernen, name='partner_entfernen'),
    path('api/personen/suche/', views.personen_suche_api, name='personen_suche_api'),
    path('verwandtschaft/', views.verwandtschaft, name='verwandtschaft'),
    path('api/verwandtschaft/', views.verwandtschaft_api, name='verwandtschaft_api'),
    path('export/gedcom/', views.export_gedcom, name='export_gedcom'),
    path('export/csv/', views.export_csv, name='export_csv'),
    path('import/', views.import_view, name='import'),
    path('stammbaum/sugiyama/', views.stammbaum_sugiyama, name='stammbaum_sugiyama'),
    path('api/stammbaum/sugiyama/', views.stammbaum_sugiyama_json, name='stammbaum_sugiyama_json'),
]
